### ISSUE TITLE
Download can't work

### ISSUE THREAD

**Issue by vince83110** [iguider/youtube-dler#3]
Since Youtube API needs OAuth to work, I can't understand you only use authentification with key in your upload example.
It doesn't work, and it can't work.

**Comment by iguider** [comment]
Thanks for your feedback,
This is actually working as shown in the following screenshot:
![youtube-dler](https://user-images.githubusercontent.com/3328396/32280609-66fcbcaa-bf14-11e7-8e57-770ba0eb1355.png)
YouTube API only requires OAuth when dealing with user specific things like uploading a video or commenting on a video as a particular user.
Since `youtube-dler` only uses the YouTube API to retrieve informations about videos and playlist only an API key is required.
